title:              20-2 OSS Team 3
email:              your-email@example.com
description:        SKKU iCampus Downloader
author:             Team 3
baseurl:            "/2020-2-OSS-3"
url:                "https://20-2-skku-oss.github.io/2020-2-OSS-3/"

# Social Profiles
twitter_username:   
github_username: "20-2-SKKU-OSS/2020-2-OSS-3"   
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
